apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: vpio
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: POC
          value: POC
        image: quay.io/redhat-appstudio-qe/byoc-xlew-tenant/byoc-app-fmda/vpio@sha256:302726b5732d601042e5acba0ab5130e55b66be715af8d5d5525dabdbcd2829f
        name: my-java-quarkus
        resources: {}
status: {}
