apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: vpio
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vpio
    app.kubernetes.io/part-of: byoc-app-fmda
  name: vpio
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: vpio
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: vpio
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-xlew-tenant/byoc-app-fmda/vpio@sha256:302726b5732d601042e5acba0ab5130e55b66be715af8d5d5525dabdbcd2829f
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
